name: cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - sphinx-pythia-theme
  - scikit-learn
  - numpy==1.26.4
  - pandas==2.2.2
  - seaborn
  - matplotlib==3.8.4
  - minisom
  - xarray
